### ISSUE TITLE
Update rfc peerDependencies

### ISSUE THREAD

**Issue by DamienSeguin** [indutny/asn1.js#31] opened 2015-01-03 16:21 UTC
Getting this error when npm installing browserify 8.0.3:
```
npm ERR! peerinvalid The package asn1.js does not satisfy its siblings' peerDependencies requirements!
```

I have found that too:
```
npm ERR! peerinvalid Peer asn1.js-rfc3280@0.5.2 wants asn1.js@^0.6.0
```

The problem comes from `browserify-sign` that references `asn1.js-rfc3280` I guess.
Updating the `package.json` peerDependencies object in the rfc 3280 from `"asn1.js": "^0.6.0"`too `0.6.6` or `0.6.x`could resolve that ?

If it is the solution, it probably has to be done in the rfc 2560 too.

**Comment by indutny** [comment] 2015-01-03 20:25
There was a problem with elliptic dependency, but it appears to be working fine for me now. Sorry, but I can't reproduce.

What node.js version are you using?

**Comment by DamienSeguin** [comment] 2015-01-03 22:10
I am using:

```
node -v v0.10.35
npm -v 1.4.28
```

**Comment by indutny** [comment] 2015-01-03 22:11
Same on my side. Could you please try `npm cache clean` and install it again?

**Comment by DamienSeguin** [comment] 2015-01-03 22:24
Nothing changed unfortunately. I think it really has to be something with node peerDependencies but it is weird you can't reproduce. I am just running ` npm install browserify`.

**Comment by indutny** [comment] 2015-01-03 22:35
Ok, I'll fix it in asn1.js

**Comment by indutny** [comment] 2015-01-03 22:39
Should be fixed.

**Closed by indutny** 2015-01-03 22:39 UTC
